// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WriteCloser is an autogenerated mock type for the WriteCloser type
type WriteCloser struct {
	mock.Mock
}

type WriteCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *WriteCloser) EXPECT() *WriteCloser_Expecter {
	return &WriteCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *WriteCloser) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type WriteCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *WriteCloser_Expecter) Close() *WriteCloser_Close_Call {
	return &WriteCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *WriteCloser_Close_Call) Run(run func()) *WriteCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WriteCloser_Close_Call) Return(_a0 error) *WriteCloser_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *WriteCloser) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteCloser_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type WriteCloser_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *WriteCloser_Expecter) Write(p interface{}) *WriteCloser_Write_Call {
	return &WriteCloser_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *WriteCloser_Write_Call) Run(run func(p []byte)) *WriteCloser_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *WriteCloser_Write_Call) Return(n int, err error) *WriteCloser_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

type mockConstructorTestingTNewWriteCloser interface {
	mock.TestingT
	Cleanup(func())
}

// NewWriteCloser creates a new instance of WriteCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWriteCloser(t mockConstructorTestingTNewWriteCloser) *WriteCloser {
	mock := &WriteCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
